### ISSUE TITLE
Error "Fatal TypeError: func is not a function"

### ISSUE THREAD

**Issue by BlueBlock** [demmer/bluebird-retry#24]
I'm starting with a function just like in the readme example. But i get the error:
"Fatal TypeError: func is not a function"

One difference, I'd like to use a function which requires parameters.

**Comment by demmer** [comment]
If you want to call a function that takes parameters, you'll need to wrap it in a closure function that can be retried. There's no way currently to pass arguments through. 

As to the error -- can you paste the full snippet of code so I can see what might be going wrong?

**Comment by BlueBlock** [comment]
Thanks.  I wrapped it in another function and it worked well.

**Comment by demmer** [comment]
OK
