### ISSUE TITLE
Feature request: retry returns Promise

### ISSUE THREAD

**Issue by ruwang** [demmer/bluebird-retry#25]
Not sure if this has been implemented yet but it seems I can't get it working. I want to get the value returned by the retry so that it can be used by next chained promise. For example,

```
const retry = require('bluebird-retry');
... ...
const result =  retry(func, { interval: 2000 }).done((res) => Promise.resolve(res));
```
I'd expect the variable `result` to be `res` promise, but it' undefined instead.
Anyway I can get the promise back after retry call?

**Comment by demmer** [comment]
This has nothing to do with bluebird-retry, it's that you're using the `.done` handler which returns undefined as noted in the [bluebird api](http://bluebirdjs.com/docs/api/done.html).

If you want a promise chain you should use `.then` at which point you can get your return value.

**Comment by ruwang** [comment]
Thanks for pointing that out!
