### ISSUE TITLE
Would you consider using fn.apply() instead of fn()?

### ISSUE THREAD

**Issue by dimvic** [demmer/bluebird-retry#34]
Using something in the lines of `fn.apply(stateObj, options.args)` would make it possible possible to call `fn` using arguments in ways cleaner than `retry(() => { return fn(a, b, c); });` and also run `fn` in a specific scope, which would allow it to keep track of what has happened in previous runs. Would this make any sense?

**Comment by demmer** [comment]
@dimvic How does #37 look? Would this suffice for what you're looking for?

**Comment by dimvic** [comment]
First of all, let me explain my use case which is a parser that retries the requests if they fail and I want to be able to break the retries if the response code is a 404. By taking a closer look I saw that I can do this without an extension to bluebird-retry:

- It is easy to pass arguments to the repeated function by using a closure that calls the actual function using variables from an upper scope as arguments
- You can terminate on 404 by using the `predicate` option (I did not have the time to try that yet, but there should be no problem)

So, yes, the PR looks great and covers exactly what I suggested, but `args` (while useful) might be an overkill after all, context should be enough.

**Comment by demmer** [comment]
Well either of those options seems fine, but the PR to add context/args is simple enough that it seems worthwhile to include, so I'll just merge that one as well.

**Comment by demmer** [comment]
Fixed with #37.
