### ISSUE TITLE
webpack compliance

### ISSUE THREAD

**Issue by amir-arad** [demmer/bluebird-retry#35]
While trying to use this otherwise great module with webpack, I get a `Cannot find module 'bluebird'` error. 
Looks as if the browserified version basically loads well in webpack, but it avoids webpack's static require substitution. :(

**Comment by amir-arad** [comment]
My temporary solution was to add a resolve.alias in webpack configuration like so:
```
alias: {
        'bluebird-retry': 'bluebird-retry/lib/bluebird-retry'
    }
```

**Comment by demmer** [comment]
@amir-arad Do you have any suggestions as to how I could change the library to be more amenable to webpack? I'm not familiar with what needs to be done but I'd welcome a PR with suggested changes to make this work.

**Comment by amir-arad** [comment]
@demmer I have the opposite problem: there's some browserify magic in the module (from PR #21 ) that I don't really understand...
