### ISSUE TITLE
Allow chaining

### ISSUE THREAD

**Issue by strarsis** [demmer/bluebird-retry#39]
It would be more intuitive if done(...) callback could be chained like thenables:
```js
retry(myfunc).done(function(result) {
    return someOtherPromiseReturning();
})
.then(function() {
    // next step
});
````

**Comment by demmer** [comment]
This has nothing to do with `bluebird-retry` per se... the problem is that you're using the discouraged `.done` callback instead of just using `.then` (http://bluebirdjs.com/docs/api/done.html).

This should work fine:
```js
retry(myfunc).then(function(result) {
    return someOtherPromiseReturning();
})
.then(function() {
    // next step
});
```

**Comment by strarsis** [comment]
It would be great if the README could be updated to use then(...) instead.

**Comment by demmer** [comment]
@strarsis Oops -- I totally missed that thanks! Just updated the README and pushed a patch release so it's on NPM as well.
