### ISSUE TITLE
Update project to use webpack

### ISSUE THREAD

**Issue by jonathanchrisp** [demmer/bluebird-retry#40]
Hey @demmer, do you mind if I update this project to use webpack? I'll produce the build with the UMD output so this can be used on both the client and server side. Have you looked into this as of yet?

**Comment by demmer** [comment]
@jonathanchrisp Sure -- TBH I'm not doing much JS work these days but this sounds like a worthy improvement as far as I'm concerned.

**Comment by jonathanchrisp** [comment]
Sounds great, I'll try and find some time over the next few days. Thanks for the quick response.

**Comment by jonathanchrisp** [comment]
Apologies for the delay, decided not to do this in the end so closing issue.
